openapi: 3.0.0
info:
  title: jobs-api
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /api/v1/jobs:
    get:
      tags:
        - jobs
      summary: All Jobs
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

    post:
      tags:
        - jobs
      summary: Create Job
      requestBody:
        content: {}
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/jobs/id:
    get:
      tags:
        - jobs
      summary: One Job
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - jobs
      summary: delete job
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}

    patch:
      tags:
        - jobs
      summary: update job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example: {}
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODE2NDFhNWRmNzMzMzQyYjgyOTg0YmUiLCJuYW1lIjoicnVraXllY2FsaSIsImlhdCI6MTc0NjI4OTA3NywiZXhwIjoxNzQ4ODgxMDc3fQ.9aQhEL0unX7Db1OoJq2iT_Kio3lHPctybkDNG2iPXhM
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/register:
    post:
      tags:
        - auth
      summary: register
      requestBody:
        content: {}
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                name: bob
                email: bob@gmail.com
                password: secret
  /api/v1/auth/login:
    post:
      tags:
        - auth
      summary: login
      requestBody:
        content: {}
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              example:
                email: bob@gmail.com
                password: secret
